apiVersion: v1
kind: ServiceAccount
metadata:
  name: taintmanager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-taint-manager
subjects:
- kind: ServiceAccount
  name: taintmanager
  namespace: default
roleRef:
  kind: ClusterRole
  name: cloud-node-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: taintremover
  namespace: default
  labels:
    app: taintremover
spec:
  selector:
    matchLabels:
      app: taintremvoer
  template:
    metadata:
      labels:
        app: taintremvoer
    spec:
      serviceAccount: taintmanager
      tolerations:
      - key: kubernetes.azure.com/scalesetpriority
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        kubernetes.io/os: windows
      initContainers:
      - name: taintremover
        image: ghcr.io/markjgardner/taintremover:0.5.47
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TAINT
          value: kubernetes.azure.com/scalesetpriority=spot:NoSchedule
      containers:
        - name: pause
          image: k8s.gcr.io/pause:3.5
      terminationGracePeriodSeconds: 30