on:
  push:
    branches:
    - main
    # for workflow dev
    - github
jobs:
  build-linux-image:
    uses: markjgardner/aks-taint-remover/.github/workflows/template.yml@github
    with:
      baseTag: "6.0-alpine"
      runner: ubuntu-latest
 