on:
  push:
    branches:
    - main
    # for workflow dev
    - github
jobs:
  build-linux-image:
    uses: markjgardner/aks-taint-remover/.github/workflows/template.yml@github
    with:
      baseTag: "6.0-alpine"
      runner: ubuntu-latest
  build-windows2019-image:
    uses: markjgardner/aks-taint-remover/.github/workflows/template.yml@github
    with:
      baseTag: "6.0-nanoserver-1809"
      runner: windows-2019
  build-windows2022-image:
    uses: markjgardner/aks-taint-remover/.github/workflows/template.yml@github
    with:
      baseTag: "6.0-nanoserver-ltsc2022"
      runner: windows-2022
  consolidate-multiarch-image:
    runs-on: ubuntu-latest
    needs: [build-linux-image, build-windows2019-image, build-windows2022-image]
    steps: 
      - run: docker manifest create ghcr.io/markjgardner/taintremover:0.4.${{ github.run_number }} 
          --amend ${{ needs.build-linux-image.outputs.fullImageName }} 
          --amend ${{ needs.build-windows2019-image.outputs.fullImageName }} 
          --amend ${{ needs.build-windows2022-image.outputs.fullImageName }}
      - run: docker manifest push ghcr.io/markjgardner/taintremover:0.4.${{ github.run_number }}