on:
  push:
    branches:
      - main
      # for workflow dev
      - github
    paths:
      - 'src/**'
      - '.github/**'
    
env:
  IMAGENAME: ghcr.io/markjgardner/taintremover
  TAG: 0.5.${{ github.run_number }}

jobs:
  #BEGIN HACK: see https://github.community/t/reusable-workflow-env-context-not-available-in-jobs-job-id-with/206111
  hack:
    runs-on: ubuntu-latest
    outputs:
      imageName: ${{ env.IMAGENAME }}
      tag: ${{ env.TAG }}
    steps:
      - run: ":"
  #END HACK  
  build-linux-image:
    uses: ./.github/workflows/template.yml
    needs: hack
    with:
      imageName: ${{ needs.hack.outputs.imageName }}
      versionTag: ${{ needs.hack.outputs.tag }}
      baseTag: "6.0-alpine"
      runner: ubuntu-latest
  build-windows2019-image:
    uses: ./.github/workflows/template.yml
    needs: hack
    with:
      imageName: ${{ needs.hack.outputs.imageName }}
      versionTag: ${{ needs.hack.outputs.tag }}
      baseTag: "6.0-nanoserver-1809"
      runner: windows-2019
  build-windows2022-image:
    uses: ./.github/workflows/template.yml
    needs: hack
    with:
      imageName: ${{ needs.hack.outputs.imageName }}
      versionTag: ${{ needs.hack.outputs.tag }}
      baseTag: "6.0-nanoserver-ltsc2022"
      runner: windows-2022
  consolidate-multiarch-image:
    runs-on: ubuntu-latest
    needs: [build-linux-image, build-windows2019-image, build-windows2022-image]
    steps: 
      - run: docker manifest create $IMAGENAME:$TAG
          --amend ${{ needs.build-linux-image.outputs.fullImageName }} 
          --amend ${{ needs.build-windows2019-image.outputs.fullImageName }} 
          --amend ${{ needs.build-windows2022-image.outputs.fullImageName }}
      
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker manifest push $IMAGENAME:$TAG