on:
  push:
    branches:
    - main
    # for workflow dev
    - github
env:
  ACR_BASE_URI: mjgcontainers.azurecr.io
  VERSION: "0.4.$GITHUB_RUN_NUMBER"
jobs:
  build-linux-image:
    uses: markjgardner/aks-taint-remover/.github/workflows/template.yml@github
    with:
      baseTag: "6.0-alpine"
      runner: ubuntu-latest
 