on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      baseTag:
        required: true
        type: string
    outputs:
      fullImageName:
        description: "The fully qualified name of the built image"
        value: ${{ jobs.build-image.outputs.imageName }}
jobs:
  build-image:
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        working-directory: ./src
    outputs:
      imageName: ${{ steps.setImageName.outputs.imageName }}
    steps:
      - uses: actions/checkout@v2
      
      - id: setImageName
        name: Set fully qualified image name
        run: echo "::set-output name=imageName::${{ env.IMAGENAME }}:${{ env.TAG }}-${{ inputs.baseTag }}"

      - name: Build image
        run: docker build -t "${{ steps.setImageName.outputs.imageName }}" --build-arg BASE_TAG=${{ inputs.baseTag }} .
      
      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to registry
        run: docker push ${{ steps.setImageName.outputs.imageName }}