on:
  workflow_call:
    inputs:
      baseTag:
        required: true
        type: string
      runner:
        required: true
        type: string
jobs:
  build-image:
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        working-directory: ./src
    env:
      ACR_BASE_URI: mjgcontainers.azurecr.io
      VERSION: "0.4.$GITHUB_RUN_NUMBER"
      BASE_TAG: ${{ inputs.baseTag }}
    steps:
    - uses: actions/checkout@v2
    - name: Build Linux Image
      run: docker build -t "$ACR_BASE_URI/taintremover:$VERSION-$BASE_TAG" --build-arg BASE_TAG=$BASE_TAG .