on:
  workflow_call:
    inputs:
      baseTag:
        required: true
        type: string
      runner:
        required: true
        type: string
env:
  ACR_BASE_URI: mjgcontainers.azurecr.io
  VERSION: "0.4"
jobs:
  build-image:
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v2
    - run: echo "Building $ACR_BASE_URI/taintremover:$VERSION-${{ inputs.baseTag }}"
    - name: Build Linux Image
      run: docker build -t "$ACR_BASE_URI/taintremover:$VERSION.$GITHUB_RUN_NUMBER-${{ inputs.baseTag }}" --build-arg BASE_TAG=${{ inputs.baseTag }} .