on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      registryName:
        required: true
        type: string
      baseTag:
        required: true
        type: string
      runner:
        required: true
        type: string
jobs:
  build-image:
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v2
    - name: Build Linux Image
      run: docker build -t "${{ inputs.registryName }}/taintremover:${{ inputs.version }}-${{ inputs.baseTag }}" \
        --build-arg BASE_TAG=${{ inputs.baseTag }} .